"""rename department

Revision ID: 57fc049bec01
Revises: 8b8ee291cc27
Create Date: 2024-10-12 20:37:08.100455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fc049bec01'
down_revision = '8b8ee291cc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
